import dbConnect from '@/lib/dbConnect';
import Project from '@/lib/models/Project';
import Board from '@/lib/models/kanban/BoardModel';
import Section from '@/lib/models/kanban/SectionModel';
import Note from '@/lib/models/kanban/NoteModel';
import Task from '@/lib/models/wbs/TaskModel';
import User from '@/lib/models/User';

/**
 * 프로젝트 전체 상태를 CLAUDE.md 형식의 마크다운으로 반환한다.
 * ENV / ACCOUNT 카테고리 리소스는 항상 제외된다.
 */
export async function buildProjectContext(pid: number): Promise<string | null> {
  await dbConnect();

  // 병렬 조회
  const project = await Project.findOne({ pid, delYn: false }).lean();
  if (!project) return null;

  const board = await Board.findOne({ pid }).lean();

  const [sections, tasks] = await Promise.all([
    board ? Section.find({ boardId: board._id }).lean() : Promise.resolve([]),
    Task.find({ pid }).lean(),
  ]);

  const notes = board
    ? await Note.find({ boardId: board._id, status: 'active' }).lean()
    : [];

  // 팀원 이름 조회 (이름만, ObjectId/이메일 제외)
  const activeMembers = project.members.filter((m) => m.status === 'active');
  const memberUserIds = activeMembers.map((m) => m.userId);
  const users = await User.find({ _id: { $in: memberUserIds } })
    .select('_id nName position')
    .lean();
  const userMap = new Map(users.map((u) => [u._id.toString(), u]));

  const lines: string[] = [];

  // ─── 헤더 ───────────────────────────────────────────────
  lines.push(`# CLAUDE.md — ${project.title}`);
  lines.push(
    `> Auto-generated by Side Project Mate | ${new Date().toISOString()}`
  );
  lines.push('> Do not edit manually. Fetch again for the latest state.');
  lines.push('');

  // ─── 프로젝트 기본 정보 ──────────────────────────────────
  lines.push('## Project');
  lines.push('');
  lines.push(`- **Status**: ${project.status}`);
  if (project.currentStage) lines.push(`- **Stage**: ${project.currentStage}`);
  if (project.executionStyle) lines.push(`- **Execution Style**: ${project.executionStyle}`);
  if (project.techStacks?.length) lines.push(`- **Tech Stack**: ${project.techStacks.join(', ')}`);
  if (project.domains?.length) lines.push(`- **Domains**: ${project.domains.join(', ')}`);
  if (project.deadline) lines.push(`- **Deadline**: ${project.deadline.toISOString().split('T')[0]}`);
  if (project.weeklyHours) lines.push(`- **Weekly Hours**: ${project.weeklyHours}h/week`);
  if (project.durationMonths) lines.push(`- **Duration**: ${project.durationMonths} months`);
  lines.push(`- **Team Size**: ${activeMembers.length} / ${project.maxMembers} members`);
  lines.push('');

  // ─── 문제 정의 ──────────────────────────────────────────
  if (project.problemStatement) {
    lines.push('## Problem Statement');
    lines.push('');
    lines.push(project.problemStatement);
    lines.push('');
  }

  // ─── 프로젝트 개요 ──────────────────────────────────────
  if (project.overview) {
    lines.push('## Overview');
    lines.push('');
    lines.push(project.overview);
    lines.push('');
  }

  // ─── 링크 ───────────────────────────────────────────────
  const links = project.links;
  const hasLinks = links && Object.values(links).some(Boolean);
  if (hasLinks) {
    lines.push('## Links');
    lines.push('');
    if (links?.github) lines.push(`- **GitHub**: ${links.github}`);
    if (links?.deploy) lines.push(`- **Deploy**: ${links.deploy}`);
    if (links?.figma) lines.push(`- **Figma**: ${links.figma}`);
    if (links?.notion) lines.push(`- **Notion**: ${links.notion}`);
    lines.push('');
  }

  // ─── 공유 리소스 (ENV, ACCOUNT 제외) ───────────────────
  const safeResources = project.resources.filter(
    (r) => r.category !== 'ENV' && r.category !== 'ACCOUNT'
  );
  if (safeResources.length > 0) {
    lines.push('## Shared Resources');
    lines.push('');
    for (const r of safeResources) {
      const label = r.metadata?.title ? `${r.metadata.title} ` : '';
      lines.push(`- [${r.category}] ${label}${r.content}`);
    }
    lines.push('');
  }

  // ─── 팀 ────────────────────────────────────────────────
  if (activeMembers.length > 0) {
    lines.push('## Team');
    lines.push('');
    for (const m of activeMembers) {
      const user = userMap.get(m.userId.toString());
      const name = user?.nName ?? '(알 수 없음)';
      const position = user?.position ? ` — ${user.position}` : '';
      const role = m.role ? ` (${m.role})` : '';
      lines.push(`- ${name}${role}${position}`);
    }
    lines.push('');
  }

  // ─── 칸반 보드 ──────────────────────────────────────────
  if (notes.length > 0) {
    lines.push('## Current Board (Kanban)');
    lines.push('');

    const sectionMap = new Map(sections.map((s) => [s._id.toString(), s]));
    const grouped = new Map<string | null, typeof notes>();

    for (const note of notes) {
      const key = note.sectionId ? note.sectionId.toString() : null;
      if (!grouped.has(key)) grouped.set(key, []);
      grouped.get(key)!.push(note);
    }

    // 섹션별 노트
    for (const [sectionId, sectionNotes] of grouped) {
      if (!sectionId) continue;
      const section = sectionMap.get(sectionId);
      if (!section) continue;
      lines.push(`### ${section.title}`);
      lines.push('');
      for (const note of sectionNotes) {
        lines.push(`- **${note.text.trim()}**`);
        if (note.tags?.length) lines.push(`  - 태그: ${note.tags.join(', ')}`);
        if (note.dueDate) lines.push(`  - 마감: ${new Date(note.dueDate).toISOString().split('T')[0]}`);
      }
      lines.push('');
    }

    // 고아 노트
    const orphans = grouped.get(null);
    if (orphans?.length) {
      lines.push('### 기타 노트');
      lines.push('');
      for (const note of orphans) {
        lines.push(`- **${note.text.trim()}**`);
        if (note.tags?.length) lines.push(`  - 태그: ${note.tags.join(', ')}`);
      }
      lines.push('');
    }
  }

  // ─── WBS 태스크 ─────────────────────────────────────────
  if (tasks.length > 0) {
    lines.push('## Task Schedule (WBS)');
    lines.push('');

    // phase별 그룹핑
    const phaseMap = new Map<string, typeof tasks>();
    for (const task of tasks) {
      const phase = task.phase || '기본';
      if (!phaseMap.has(phase)) phaseMap.set(phase, []);
      phaseMap.get(phase)!.push(task);
    }

    for (const [phase, phaseTasks] of phaseMap) {
      lines.push(`### ${phase}`);
      lines.push('');
      lines.push('| Task | Status | Progress | Start | End | Milestone |');
      lines.push('|------|--------|----------|-------|-----|-----------|');
      for (const task of phaseTasks) {
        const start = task.startDate ? new Date(task.startDate).toISOString().split('T')[0] : '-';
        const end = task.endDate ? new Date(task.endDate).toISOString().split('T')[0] : '-';
        const milestone = task.milestone ? '✓' : '';
        lines.push(
          `| ${task.title} | ${task.status} | ${task.progress}% | ${start} | ${end} | ${milestone} |`
        );
      }
      lines.push('');
    }
  }

  return lines.join('\n').trimEnd();
}
